In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('DataGaji.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Bandung' 35.0 3400000.0]
 ['Bogor' nan 6100000.0]
 ['Cirebon' 42.0 6500000.0]
 ['Bandung' nan 4900000.0]
 ['Bogor' 40.0 6400000.0]
 ['Bandung' 35.0 nan]
 ['Bandung' 30.0 7200000.0]
 ['Cirebon' 48.0 4800000.0]
 ['Cirebon' 39.0 5200000.0]
 ['Bandung' 48.0 5400000.0]
 ['Bandung' 37.0 6700000.0]
 ['Cirebon' 44.0 4300000.0]
 ['Bogor' 38.0 nan]
 ['Bogor' 45.0 8300000.0]
 ['Cirebon' 30.0 nan]]


In [4]:
print(y)

['Sudah' 'Belum' 'Belum' 'Belum' 'Sudah' 'Sudah' 'Belum' 'Sudah' 'Belum'
 'Sudah' 'Sudah' 'Sudah' 'Belum' 'Belum' 'Sudah']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['Bandung' 35.0 3400000.0]
 ['Bogor' 39.30769230769231 6100000.0]
 ['Cirebon' 42.0 6500000.0]
 ['Bandung' 39.30769230769231 4900000.0]
 ['Bogor' 40.0 6400000.0]
 ['Bandung' 35.0 5766666.666666667]
 ['Bandung' 30.0 7200000.0]
 ['Cirebon' 48.0 4800000.0]
 ['Cirebon' 39.0 5200000.0]
 ['Bandung' 48.0 5400000.0]
 ['Bandung' 37.0 6700000.0]
 ['Cirebon' 44.0 4300000.0]
 ['Bogor' 38.0 5766666.666666667]
 ['Bogor' 45.0 8300000.0]
 ['Cirebon' 30.0 5766666.666666667]]


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))                    

In [13]:
print(x)

[[1.0 0.0 0.0 35.0 3400000.0]
 [0.0 1.0 0.0 39.30769230769231 6100000.0]
 [0.0 0.0 1.0 42.0 6500000.0]
 [1.0 0.0 0.0 39.30769230769231 4900000.0]
 [0.0 1.0 0.0 40.0 6400000.0]
 [1.0 0.0 0.0 35.0 5766666.666666667]
 [1.0 0.0 0.0 30.0 7200000.0]
 [0.0 0.0 1.0 48.0 4800000.0]
 [0.0 0.0 1.0 39.0 5200000.0]
 [1.0 0.0 0.0 48.0 5400000.0]
 [1.0 0.0 0.0 37.0 6700000.0]
 [0.0 0.0 1.0 44.0 4300000.0]
 [0.0 1.0 0.0 38.0 5766666.666666667]
 [0.0 1.0 0.0 45.0 8300000.0]
 [0.0 0.0 1.0 30.0 5766666.666666667]]


In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:
print(y)

[1 0 0 0 1 1 0 1 0 1 1 1 0 0 1]


In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [19]:
print(x_train)

[[0.0 0.0 1.0 42.0 6500000.0]
 [1.0 0.0 0.0 37.0 6700000.0]
 [0.0 1.0 0.0 40.0 6400000.0]
 [0.0 1.0 0.0 39.30769230769231 6100000.0]
 [0.0 1.0 0.0 45.0 8300000.0]
 [1.0 0.0 0.0 35.0 3400000.0]
 [0.0 0.0 1.0 30.0 5766666.666666667]
 [1.0 0.0 0.0 48.0 5400000.0]
 [0.0 0.0 1.0 39.0 5200000.0]
 [0.0 1.0 0.0 38.0 5766666.666666667]
 [0.0 0.0 1.0 44.0 4300000.0]
 [1.0 0.0 0.0 35.0 5766666.666666667]]


In [20]:
print(x_test)

[[1.0 0.0 0.0 39.30769230769231 4900000.0]
 [0.0 0.0 1.0 48.0 4800000.0]
 [1.0 0.0 0.0 30.0 7200000.0]]


In [21]:
print(y_train)

[0 1 1 0 0 1 1 1 0 0 1 1]


In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [24]:
print(x_train)

[[0.0 0.0 1.0 0.5582799333500841 0.5963599259594181]
 [1.0 0.0 0.0 -0.4986578045457057 0.7667484762335376]
 [0.0 1.0 0.0 0.1355048381917682 0.5111656508223583]
 [0.0 1.0 0.0 -0.010840387055341395 0.25558282541117916]
 [0.0 1.0 0.0 1.1924425760875579 2.129856878426493]
 [1.0 0.0 0.0 -0.9214328997040215 -2.0446626032894333]
 [0.0 0.0 1.0 -1.9783706375998114 -0.02839809171235298]
 [1.0 0.0 0.0 1.826605218825032 -0.3407771005482389]
 [0.0 0.0 1.0 -0.07588270938738977 -0.5111656508223583]
 [0.0 1.0 0.0 -0.28727025696654773 -0.02839809171235298]
 [0.0 0.0 1.0 0.9810550285084 -1.277914127055896]
 [1.0 0.0 0.0 -0.9214328997040215 -0.02839809171235298]]


In [25]:
print(x_test)

[[1.0 0.0 0.0 -0.010840387055341395 -0.7667484762335376]
 [0.0 0.0 1.0 1.826605218825032 -0.8519427513705973]
 [1.0 0.0 0.0 -1.9783706375998114 1.1927198519188362]]
